### PR TITLE
Rename LICENCE to LICENSE

### PR DESCRIPTION
**Pull request by PixnBits**
spelling fix

### CODE REVIEW

**Comment by shellscape** [comment]
:+1:

**Comment by alanshaw** [comment]
Is there a particular reason to do this? The spelling is not a fix for me.

**Comment by shellscape** [comment]
I suppose if you're not American, this doesn't look wrong. If you are American, it's incorrect. Correcting spelling is a fix, imho. If this project is localized to a country other than the US, it should be closed as invalid; as "licence" is a noun and "license" is a verb, outside of the US.

**Comment by PixnBits** [comment]
"whilst" is in the changelog, closing as the discrepancy is purely i18n/l10n

**Comment by shellscape** [comment]
:+1:  makes sense to me. fwiw, "whilst" is getting more use in the American dialect these days.

**Pull request closed without merging**
