### PR TITLE
Allow package.json to be user specified

### PR DESCRIPTION
**Pull request by kingcody**

### CODE REVIEW

**Comment by kingcody** [comment]
@alanshaw if this is an acceptable PR please let me know if there is anything else that should be taken care of, thanks.

**Comment by alanshaw** [comment]
Looks great, thanks!

**Comment by kingcody** [comment]
If its not too much to ask for, would you mind doing an npm release in the near future? I'd like to follow up this PR with another to `grunt-david` that allows passing the `--package` flag. Thanks again (:

**Comment by alanshaw** [comment]
Yep I'll release today! Thanks again

**Pull request merged**
