### PR TITLE
add-npm-registry-client

### PR DESCRIPTION
**Pull request by RnbWd**
fixed compatibility with npm v3.4.x

### CODE REVIEW

**Comment by alanshaw** [comment]
Not sure I understand what the problem is/was here?...#89 seems to have passing builds...

**Comment by RnbWd** [comment]
There was a dependency issue for that version of NPM - I think it was fixed by the next release  It had something to do with flattening the dependency tree to be less repetitive / minimalistic. The error would be something like 'cannot find module `nom-registry-client`' - I don't know why - but explicitly including it in the package.json fixed the error. The tests might not have resolved dependencies the same as my local machine - and I think it was an NPM problem - probably fixed now with newer versions of npm - but might be safe to add this - also might not be necessary anymore - i dunno

**Comment by alanshaw** [comment]
thanks for taking the time @RnbWd :)

**Comment by RnbWd** [comment]
NP!

just noticed this issue: https://github.com/alanshaw/david/issues/33

If there's still  help wanted I can look into it - might be a good idea

**Comment by alanshaw** [comment]
yes, if it is possible then I'd much rather use just the client...not sure if we can for install though (CLI component allows you to `david update` to install updated deps)

**Comment by RnbWd** [comment]
I usually spawn processes like this lib https://github.com/mattdesl/spawn-npm-install - but I  don't know if it would work universally

**Pull request closed without merging**
